// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzUXa-GHWe32UF6JbjNIu8-9x3OkJ2jxs',
    appId: '1:120530256895:web:f6b5ce69241ec3e58a5dca',
    messagingSenderId: '120530256895',
    projectId: 'cmtp2-7aed3',
    authDomain: 'cmtp2-7aed3.firebaseapp.com',
    storageBucket: 'cmtp2-7aed3.appspot.com',
    measurementId: 'G-HGEFW5DEMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHtnhHsMPmYsjA514zTO-hVt3qR8Zzotk',
    appId: '1:120530256895:android:a35a3c33f5864f918a5dca',
    messagingSenderId: '120530256895',
    projectId: 'cmtp2-7aed3',
    storageBucket: 'cmtp2-7aed3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD66acKHmCkJMglH0BHIa_7bxAony6ZnFI',
    appId: '1:120530256895:ios:14b8c3126cac58ab8a5dca',
    messagingSenderId: '120530256895',
    projectId: 'cmtp2-7aed3',
    storageBucket: 'cmtp2-7aed3.appspot.com',
    iosBundleId: 'com.example.aplicacao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD66acKHmCkJMglH0BHIa_7bxAony6ZnFI',
    appId: '1:120530256895:ios:520d7ac8d03441c08a5dca',
    messagingSenderId: '120530256895',
    projectId: 'cmtp2-7aed3',
    storageBucket: 'cmtp2-7aed3.appspot.com',
    iosBundleId: 'com.example.aplicacao.RunnerTests',
  );
}
